### ISSUE TITLE
Games

### ISSUE THREAD

**Issue by Atharvp18** [CO18347/HACKTOBERFEST-DS-ALGOS#23]
Please assign me this task, I will add 2 command line games that I have made using python!

**Comment by gb07bh** [comment]
Hey, I would like to add a GUI-made game( Brick Breaker) with python (Tkinter lib) in this repository.

**Comment by CO18347** [comment]
Yeah sure

**Comment by Atharvp18** [comment]
Please assign me the task, so I can add the games.

**Comment by gb07bh** [comment]
@CO18301 Could you please assign me the task :).
